## application.properties
```properties
spring.application.name=user-service
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=postgres
spring.datasource.password=Ayush@0943
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=your-256-bit-secret-key-here-make-it-long-enough
jwt.expiration=86400000
jwt.refresh-expiration=604800000
```
